
name: Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: prepare environment
        run:  sudo apt install git &&
              git submodule update --init

      - name: Build packages
        id: build_packages
        run: |
          docker run -v `pwd`:`pwd` -w `pwd` --cap-add=SYS_PTRACE -t rusdevops/bootstrap-cpp scripts/package.sh
          cd _artifacts
          DEB_PACKAGE_NAME=$(ls *.deb | tail -n 1)
          RPM_PACKAGE_NAME=$(ls *.rpm | tail -n 1)
          echo "::set-output name=deb_package_filename::$DEB_PACKAGE_NAME"
          echo "::set-output name=rpm_package_filename::$RPM_PACKAGE_NAME"
      
      
